version: 2

jobs:
  build:
    docker:
      - image: nemtrif/utf8cpp:4.0.0
    steps:
      - checkout
      - run: git submodule update --init --recursive --remote
      - run: mkdir -p tests/build
      - run: cd tests/build && cmake ..
      - run: cd tests/build && cmake --build .
      - run: cd tests/build && ctest -VV
